### ISSUE TITLE
Add more explanatory steps to AI module

### ISSUE THREAD

**Issue by vermegi** [Azure-Samples/java-microservices-aca-lab#47] opened 2024-09-20 11:39 UTC
Currently the learner doesn't know/see what they are adding/doing. We should better explain these steps.

**Comment by sonwan2020** [comment] 2024-09-27 06:58
this is duplicate of #45

**Closed** 2024-09-27 06:57 UTC

**Comment by vermegi** [comment] 2024-09-27 07:02
Not necessarily duplicate, since this ask is for the AI module, the other ask is for the azd module. 
Let me know in case you want help adding those explanatory steps.
